init:
  - git config --global core.autocrlf true
clone_depth: 1
test: off
services:
  - mongodb
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
matrix:
  fast_finish: true
for:
  -
    matrix:
      only:
        - image: Ubuntu
    build_script:
      - sh: chmod +x ./run.sh
      - sh: ./run.sh default-build
  -
    matrix:
      only:
        - image: Visual Studio 2017
    build_script:
      - ps: .\run.ps1 default-build
artifacts:
  - path: 'artifacts\build\*.nupkg'
    name: MyGet
deploy:
  - provider: Environment
    name: MyGet
    artifact: 'artifacts\build\*.nupkg'
    on:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
image:
- Ubuntu
- Visual Studio 2017
